version: '3.8'

services:
  capstone-gradio:
    build: .
    container_name: capstone-gradio-app
    ports:
      - "7860:7860"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - PYTHONPATH=/app
    volumes:
      # Mount data directories for persistence
      - ./gemini-gradio-poc/data/sessions:/app/data/sessions
      - ./gemini-gradio-poc/conversations:/app/conversations
      - ./gemini-gradio-poc/logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
