package com.myspace.recomendacion_empleados_demo_ie;
import java.util.Map;
import java.util.HashMap;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeRecommendation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String calculationDateTime;
	private java.lang.Integer restaurantEmployees = 0;
	private java.lang.Integer restaurantExtraEmployees = 0;
	private java.lang.Integer homeDeliveryEmployees = 0;

	private java.lang.String companyId;

	private java.lang.String restaurantId;

	public EmployeeRecommendation() {
	}

	public java.lang.String getCalculationDateTime() {
		return this.calculationDateTime;
	}

	public void setCalculationDateTime(java.lang.String calculationDateTime) {
		this.calculationDateTime = calculationDateTime;
	}

	public java.lang.Integer getRestaurantEmployees() {
		return this.restaurantEmployees;
	}

	public void setRestaurantEmployees(java.lang.Integer restaurantEmployees) {
		this.restaurantEmployees = restaurantEmployees;
	}

	public java.lang.Integer getRestaurantExtraEmployees() {
		return this.restaurantExtraEmployees;
	}

	public void setRestaurantExtraEmployees(
			java.lang.Integer restaurantExtraEmployees) {
		this.restaurantExtraEmployees = restaurantExtraEmployees;
	}

	public java.lang.Integer getHomeDeliveryEmployees() {
		return this.homeDeliveryEmployees;
	}

	public void setHomeDeliveryEmployees(java.lang.Integer homeDeliveryEmployees) {
		this.homeDeliveryEmployees = homeDeliveryEmployees;
	}

	public java.lang.String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(java.lang.String companyId) {
		this.companyId = companyId;
	}

	public java.lang.String getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(java.lang.String restaurantId) {
		this.restaurantId = restaurantId;
	}

	}
	
	public void addRestaurantEmployees(int restaurantEmployees){
	    this.restaurantEmployees += restaurantEmployees;
	}
	
	public void addRestaurantExtraEmployees(int restaurantExtraEmployees){
	    this.restaurantExtraEmployees += restaurantExtraEmployees;
	}
	


	public EmployeeRecommendation(java.lang.String calculationDateTime,
			java.lang.Integer restaurantEmployees,
			java.lang.Integer restaurantExtraEmployees,
			java.lang.Integer homeDeliveryEmployees,
			java.lang.String companyId, java.lang.String restaurantId) {
		this.calculationDateTime = calculationDateTime;
		this.restaurantEmployees = restaurantEmployees;
		this.restaurantExtraEmployees = restaurantExtraEmployees;
		this.homeDeliveryEmployees = homeDeliveryEmployees;
		this.companyId = companyId;
		this.restaurantId = restaurantId;
	}

}